### ISSUE TITLE
Issue running

### ISSUE THREAD

**Issue by mikkihugo** [BoBiene/PhosconToOpenHAB#1]
Hi,

Im trying to run but get the following error

Failed: System.NullReferenceException: Object reference not set to an instance of an object.
   at PhosconToOpenHAB.Program.CreateItems(StreamWriter itemsFile, PhosconBridge brige, Dictionary`2 sensors) in C:\Users\bo_bi\Source\Repos\PhosconToOpenHAB\PhosconToOpenHAB\Program.cs:line 78
   at PhosconToOpenHAB.Program.Main(String[] args) in C:\Users\bo_bi\Source\Repos\PhosconToOpenHAB\PhosconToOpenHAB\Program.cs:line 48

**Comment by BoBiene** [comment]
@mikkihugo Shuld be fixed with .NET Core 3.1 / Docker.
